version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/bassline-frontend
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: scripts/build_code.sh
      timeout: 1800
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 30
      runas: root
